name: Bug Report
description: File a bug report
title: "[BUG] "
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity of the bug.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: dropdown
    id: business-impact
    attributes:
      label: Business Impact
      description: Select the business impact of the bug.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please describe the bug you are experiencing.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmations
      description: Please confirm the following:
      options:
        - label: I have searched the existing issues
          required: true
        - label: This is a complete report with replication steps
          required: true
