name: Bug Report
description: File a bug report
title: "[BUG] "
body:
  - type: dropdown
    id: severity
    attributes:
      label: severity
      description: Select the severity of the bug.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: impact
      description: Select the business impact of the bug.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please describe the bug you are experiencing.
      placeholder: Describe the bug...
    validations:
      required: true
