name: Calculate Issue Score and Update Project Field

on:
  issues:
    types: [opened, edited]

jobs:
  update-score:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate score
        id: score-calculator
        run: |
          # Map text options to scores
          declare -A scores=(["Low"]=1 ["Medium"]=2 ["High"]=3 ["Critical"]=4)

          # Extract selections from the issue body
          severity=$(jq --raw-output '.issue.body | .[] | select(.id=="severity") | .value' $GITHUB_EVENT_PATH)
          business_impact=$(jq --raw-output '.issue.body | .[] | select(.id=="business-impact") | .value' $GITHUB_EVENT_PATH)

          # Calculate average score
          severity_score=${scores[$severity]}
          business_impact_score=${scores[$business_impact]}
          average_score=$(( (severity_score + business_impact_score) / 2 ))

          # Set the output
          echo "::set-output name=average_score::$average_score"

      - name: Update GitHub Project field
        uses: some-action/update-project-field@v1
        with:
          project-id: "PVT_kwHOARXQmM4AnIAT"
          field-id: "PVTF_lAHOARXQmM4AnIATzge6Yn8"
          issue-number: ${{ github.event.issue.number }}
          score: ${{ steps.score-calculator.outputs.average_score }}
